### ISSUE TITLE
Add current hour highlight 

### ISSUE THREAD

**Issue by RedstoneMedia** [RedstoneMedia/HAG-Crappy-Timetable-App#1]
## Describe the feature you'd like
Highlight the current hour that falls into the start and end time, like it is done WeekdayGridObject.

## Describe why you think your feature is important
We display the current day but not the current hour that is not ideal.
Also @GreenOpposite needs to do something and my brain is to stupid to deal with the date math in dart (that last part might be the real reason I created this issue).

**Comment by GreenOpposite** [comment]
Implemented in commit d0908d7e29891ef4ff5c34fb93e90e49f016e86f
