### ISSUE TITLE
Add an intro screen

### ISSUE THREAD

**Issue by GreenOpposite** [RedstoneMedia/HAG-Crappy-Timetable-App#13]
I created a design for an intro screen, which would be displayed the first time you open the app:

## Selecting your class:
![Klasse](https://user-images.githubusercontent.com/15072649/120817639-298c9000-c552-11eb-95ba-2a64c94ffd6e.jpg)

## Selecting a Theme:
![Theme](https://user-images.githubusercontent.com/15072649/120817646-2abdbd00-c552-11eb-90b2-71315c884a01.jpg)

## Configuring a custom Theme:
![Theme – Custom](https://user-images.githubusercontent.com/15072649/120817645-2abdbd00-c552-11eb-8171-35ad0f91687d.jpg)

## Adding courses:
![Kurse](https://user-images.githubusercontent.com/15072649/120817642-2a252680-c552-11eb-8120-da99826b9164.jpg)

@RedstoneMedia is there anything you would change?

**Comment by RedstoneMedia** [comment]
Looks good 👍 ! Except the light modal when customizing the theme.

**Comment by RedstoneMedia** [comment]
- [x] Class select page
- [x] Theme select page
- [x] Course select page
