### ISSUE TITLE
Add option to automaticly extract course list from image

### ISSUE THREAD

**Issue by RedstoneMedia** [RedstoneMedia/HAG-Crappy-Timetable-App#20]
## Describe the feature you'd like
It would be nice to have a feature that allows the user to take an image of a timetable printed on paper and extracts the course names from that image.

This feature could be displayed in the course list intro screen with a button that instructs the user to take an image of their timetable paper.

## Describe why you think your feature is important
This is feature would help new users setup their correct courses faster (Just take a photo and your course list is now correct), because every student usually gets a printed timetable when their timetable changes substantially.

**Comment by GreenOpposite** [comment]
Here are some design ideas for this feature.

![Kurse – Methode](https://user-images.githubusercontent.com/15072649/132103686-917470a4-f9b1-42cb-a0d0-148072475992.png)
![Kurse – Automatisch](https://user-images.githubusercontent.com/15072649/132103691-4587d262-e233-46e5-87e6-77f2d0fa765a.png)
![Kurse – Automatisch – Ergebnis](https://user-images.githubusercontent.com/15072649/132103693-f1b01865-634b-4a73-9951-5544f2f03fd6.png)

**Comment by RedstoneMedia** [comment]
Nice ! That looks wonderful. :+1:
