### ISSUE TITLE
The App is broken

### ISSUE THREAD

**Issue by GreenOpposite** [RedstoneMedia/HAG-Crappy-Timetable-App#3]
**Describe the bug and what you did in the app when the bug happened**
The Timetable parsing fails.

**Expected behaviour**
It shouldn't.

**Screenshots**
no.

**Smartphone:**
 - Device: Unimportant
 - Android version: Unimportant

**Additional context**
The website probably changed. There is no `"Nr."` in `headerColumnStringIndexMap; [parse_timetable.dart:116]` causing the length to be null.

**Please don't forget to add a severity label (Low, Medium or High)**
✔

**Comment by RedstoneMedia** [comment]
This Problem is almost impossible to fix on the client side. The data source website has been modified in a way which makes it almost impossible to use the footnote table in a relay able way.
