### ISSUE TITLE
Save file data in one file instead of saving them in 2

### ISSUE THREAD

**Issue by RedstoneMedia** [RedstoneMedia/HAG-Crappy-Timetable-App#5]
Wouldn't it make sense, if we saved the file data in one file instead of 2. That means we can get rid of some duplicate code in `loadProfileManagerAndThemeFromFiles` and might even be able to refactor shared state, so we can use it for both file and local storage saving.

Is there a reason you implemented it this way ? @GreenOpposite 
I would be happy to do the refactoring (I also need some of that juicy green on my profile 🟩)

**Comment by GreenOpposite** [comment]
There is no real reason why I did that. Feel free to refractor that.

**Comment by RedstoneMedia** [comment]
Ok good I'll be working on this then over the days.
