### ISSUE TITLE
Visually indicating holidays

### ISSUE THREAD

**Issue by RedstoneMedia** [RedstoneMedia/HAG-Crappy-Timetable-App#8]
## Describe the feature you'd like
Visually indicating holidays (Only German holidays).
The normal substitutions should still apply, since the holiday calendar data might not always be correct.

## Describe why you think your feature is important
It's useful to know if you might not have school in advance, because substitutions only apply for the next day.

**Comment by GreenOpposite** [comment]
I found this API: https://deutsche-feiertage-api.de/

**Comment by RedstoneMedia** [comment]
I don't know if it's smart to use an API, because that makes us dependent on that API. If we can figure out the holidays on the client we should definitely do that. We can however take some "inspiration" from that APIs code.

**Comment by RedstoneMedia** [comment]
- [x] Yes
- [ ] No
